# Generated by Django 5.2.3 on 2025-06-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject_expertise', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('English', 'English'), ('Social Studies', 'Social Studies'), ('Computer Science', 'Computer Science'), ('Other', 'Other')], max_length=50)),
                ('experience', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=255)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
