# Generated by Django 5.2.3 on 2025-06-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_careerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('student_class', models.CharField(max_length=10)),
                ('curriculum', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=150)),
                ('subjects', models.JSONField(default=list)),
                ('time_slot', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
