# Generated by Django 5.2.3 on 2025-06-30 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tuitionadmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
